name: project
version: 1.0.0+1
description: template
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  formz: ^0.4.1
  get_it: ^7.2.0
  injectable: ^2.1.0
  connectivity_plus: ^3.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  flutter_screenutil: ^5.6.0
  cached_network_image: ^3.2.3
  skeletons: ^0.0.3
  flutter_dotenv: ^5.0.2
  fluttertoast: ^8.1.2
  flutter_gen_runner: ^5.1.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dartz: ^0.10.1
  url_launcher: ^6.1.7
  get_cli: ^0.2.30
  get: 4.6.5
  flutter: 
    sdk: flutter
  equatable: ^2.0.5

dev_dependencies: 
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  source_gen: ^1.2.6
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

